DROP TABLE usertable;

CREATE TABLE "usertable" (
    "YCSB_KEY" CHARACTER VARYING(255),
    "FIELD1" CHARACTER VARYING(255),
    "FIELD2" CHARACTER VARYING(255),
    "FIELD3" CHARACTER VARYING(255),
    "FIELD4" CHARACTER VARYING(255),
    "FIELD5" CHARACTER VARYING(255),
    "FIELD6" CHARACTER VARYING(255),
    "FIELD7" CHARACTER VARYING(255),
    "FIELD8" CHARACTER VARYING(255),
    "FIELD9" CHARACTER VARYING(255),
    "FIELD10" CHARACTER VARYING(255),
    PRIMARY KEY("YCSB_KEY")
);